In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("../Datasets/Dataset_regression.csv")
dataset.head(3)

,area_sqft,bedrooms,bathrooms,house_age,distance_city_km,income_k,rooms,crime_rate,garage_spaces,school_rating,price
0,3774.0,1.0,4.4,44.0,12.41,24.58,9.0,3.93,2.0,4.9,881889.277081
1,4107.0,5.0,NaN,25.0,34.27,113.32,3.0,3.57,2.0,6.2,752923.379433
2,1460.0,4.0,1.6,38.0,30.12,21.81,11.0,11.17,1.0,6.3,237217.344515

In [7]:
# For simple linear reg lets use only the firts column to predict price 
X=dataset.iloc[:,0:1]
X.head()

   area_sqft
0     3774.0
1     4107.0
2     1460.0
3     1894.0
4     1730.0

In [8]:
y=dataset.iloc[:,-1]

In [9]:
y.head()

0    881889.277081
1    752923.379433
2    237217.344515
3    453706.228068
4    652759.993302
Name: price, dtype: float64

In [10]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   area_sqft         941 non-null    float64
 1   bedrooms          951 non-null    float64
 2   bathrooms         953 non-null    float64
 3   house_age         950 non-null    float64
 4   distance_city_km  945 non-null    float64
 5   income_k          948 non-null    float64
 6   rooms             943 non-null    float64
 7   crime_rate        952 non-null    float64
 8   garage_spaces     960 non-null    float64
 9   school_rating     951 non-null    float64
 10  price             1000 non-null   float64
dtypes: float64(11)
memory usage: 86.1 KB

# Lets first fix missing values

In [12]:
dataset.head()

,area_sqft,bedrooms,bathrooms,house_age,distance_city_km,income_k,rooms,crime_rate,garage_spaces,school_rating,price
0,3774.0,1.0,4.4,44.0,12.41,24.58,9.0,3.93,2.0,4.9,881889.277081
1,4107.0,5.0,NaN,25.0,34.27,113.32,3.0,3.57,2.0,6.2,752923.379433
2,1460.0,4.0,1.6,38.0,30.12,21.81,11.0,11.17,1.0,6.3,237217.344515
3,1894.0,1.0,3.8,27.0,24.84,145.98,6.0,5.14,2.0,7.9,453706.228068
4,1730.0,5.0,3.3,4.0,25.72,69.03,5.0,7.84,3.0,9.6,652759.993302

In [15]:

from sklearn.impute import SimpleImputer

In [17]:
imputer=SimpleImputer(missing_values=np.nan,strategy="mean")
imputer.fit(dataset.iloc[:,:-1])
dataset.iloc[:,:-1]=imputer.transform(dataset.iloc[:,:-1])

In [18]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   area_sqft         1000 non-null   float64
 1   bedrooms          1000 non-null   float64
 2   bathrooms         1000 non-null   float64
 3   house_age         1000 non-null   float64
 4   distance_city_km  1000 non-null   float64
 5   income_k          1000 non-null   float64
 6   rooms             1000 non-null   float64
 7   crime_rate        1000 non-null   float64
 8   garage_spaces     1000 non-null   float64
 9   school_rating     1000 non-null   float64
 10  price             1000 non-null   float64
dtypes: float64(11)
memory usage: 86.1 KB