In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

In [2]:
dataset=pd.read_csv("../Datasets/Dataset_regression.csv")
dataset.head(3)

,area_sqft,bedrooms,bathrooms,house_age,distance_city_km,income_k,rooms,crime_rate,garage_spaces,school_rating,price
0,3774.0,1.0,4.4,44.0,12.41,24.58,9.0,3.93,2.0,4.9,881889.277081
1,4107.0,5.0,NaN,25.0,34.27,113.32,3.0,3.57,2.0,6.2,752923.379433
2,1460.0,4.0,1.6,38.0,30.12,21.81,11.0,11.17,1.0,6.3,237217.344515

In [10]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   area_sqft         941 non-null    float64
 1   bedrooms          951 non-null    float64
 2   bathrooms         953 non-null    float64
 3   house_age         950 non-null    float64
 4   distance_city_km  945 non-null    float64
 5   income_k          948 non-null    float64
 6   rooms             943 non-null    float64
 7   crime_rate        952 non-null    float64
 8   garage_spaces     960 non-null    float64
 9   school_rating     951 non-null    float64
 10  price             1000 non-null   float64
dtypes: float64(11)
memory usage: 86.1 KB

# Lets first fix missing values

In [12]:
dataset.head()

,area_sqft,bedrooms,bathrooms,house_age,distance_city_km,income_k,rooms,crime_rate,garage_spaces,school_rating,price
0,3774.0,1.0,4.4,44.0,12.41,24.58,9.0,3.93,2.0,4.9,881889.277081
1,4107.0,5.0,NaN,25.0,34.27,113.32,3.0,3.57,2.0,6.2,752923.379433
2,1460.0,4.0,1.6,38.0,30.12,21.81,11.0,11.17,1.0,6.3,237217.344515
3,1894.0,1.0,3.8,27.0,24.84,145.98,6.0,5.14,2.0,7.9,453706.228068
4,1730.0,5.0,3.3,4.0,25.72,69.03,5.0,7.84,3.0,9.6,652759.993302

In [15]:

from sklearn.impute import SimpleImputer

In [17]:
imputer=SimpleImputer(missing_values=np.nan,strategy="mean")
imputer.fit(dataset.iloc[:,:-1])
dataset.iloc[:,:-1]=imputer.transform(dataset.iloc[:,:-1])

In [18]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   area_sqft         1000 non-null   float64
 1   bedrooms          1000 non-null   float64
 2   bathrooms         1000 non-null   float64
 3   house_age         1000 non-null   float64
 4   distance_city_km  1000 non-null   float64
 5   income_k          1000 non-null   float64
 6   rooms             1000 non-null   float64
 7   crime_rate        1000 non-null   float64
 8   garage_spaces     1000 non-null   float64
 9   school_rating     1000 non-null   float64
 10  price             1000 non-null   float64
dtypes: float64(11)
memory usage: 86.1 KB

In [19]:
X=dataset.iloc[:,:-1]
y=dataset.iloc[:,-1]

In [21]:
X

,area_sqft,bedrooms,bathrooms,house_age,distance_city_km,income_k,rooms,crime_rate,garage_spaces,school_rating
0,3774.000000,1.0,4.400000,44.0,12.41,24.58,9.000000,3.93,2.0,4.9
1,4107.000000,5.0,2.747954,25.0,34.27,113.32,3.000000,3.57,2.0,6.2
2,1460.000000,4.0,1.600000,38.0,30.12,21.81,11.000000,11.17,1.0,6.3
3,1894.000000,1.0,3.800000,27.0,24.84,145.98,6.000000,5.14,2.0,7.9
4,1730.000000,5.0,3.300000,4.0,25.72,69.03,5.000000,7.84,3.0,9.6
...,...,...,...,...,...,...,...,...,...,...
995,2084.000000,1.0,2.400000,40.0,15.27,121.56,6.954401,13.76,2.0,8.8
996,2233.000000,5.0,4.200000,28.0,2.72,49.83,10.000000,2.92,2.0,6.9
997,2752.000000,3.0,3.500000,8.0,2.34,139.90,6.000000,2.26,0.0,4.3
998,3770.000000,2.0,3.100000,12.0,20.51,107.31,8.000000,1.74,0.0,6.3
999,2561.605739,3.0,2.100000,5.0,14.36,52.65,7.000000,13.69,2.0,9.8

In [22]:
y

0      881889.277081
1      752923.379433
2      237217.344515
3      453706.228068
4      652759.993302
           ...
995    582541.947060
996    925061.912148
997    897998.490678
998    824286.488731
999    542196.407875
Name: price, Length: 1000, dtype: float64

# **Dataset for Simple Regression**

In [23]:
X_dataset_reg=dataset.iloc[:,0:1]
y=dataset.iloc[:,-1]

In [24]:
X_dataset_reg

       area_sqft
0    3774.000000
1    4107.000000
2    1460.000000
3    1894.000000
4    1730.000000
..           ...
995  2084.000000
996  2233.000000
997  2752.000000
998  3770.000000
999  2561.605739

[1000 rows x 1 columns]

In [25]:
y

0      881889.277081
1      752923.379433
2      237217.344515
3      453706.228068
4      652759.993302
           ...
995    582541.947060
996    925061.912148
997    897998.490678
998    824286.488731
999    542196.407875
Name: price, Length: 1000, dtype: float64