In [1]:
import pandas as pd
import matplotlib.pyplot as plt 
import numpy as np

In [2]:
dataset=pd.read_csv("dataset.csv")

In [4]:
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [5]:
print(X)

[['Spain' 44.0 72000.0]
 ['Germany' 27.0 48000.0]
 ['India' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['India' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['Germany' 48.0 79000.0]
 ['India' 50.0 83000.0]
 ['Spain' 37.0 67000.0]
 ['Africa' 29.0 nan]
 ['Germany' 33.0 59000.0]
 ['India' nan 49000.0]
 ['Spain' 42.0 71000.0]
 ['Africa' 45.0 76000.0]
 ['Germany' 31.0 55000.0]
 ['India' 28.0 nan]
 ['Spain' nan 64000.0]
 ['Africa' 39.0 62000.0]
 ['Germany' 36.0 68000.0]]

In [6]:
print(y)

<StringArray>
[ 'No', 'Yes',  'No',  'No', 'Yes', 'Yes',  'No', 'Yes',  'No', 'Yes',  'No',
 'Yes',  'No', 'Yes',  'No', 'Yes',  'No', 'Yes',  'No', 'Yes']
Length: 20, dtype: str

In [7]:
dataset.describe()

             Age        Salary
count  17.000000     17.000000
mean   37.176471  63411.764706
std     7.037714  10434.670716
min    27.000000  48000.000000
25%    31.000000  55000.000000
50%    37.000000  62000.000000
75%    42.000000  71000.000000
max    50.000000  83000.000000

In [8]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    20 non-null     str
 1   Age        17 non-null     float64
 2   Salary     17 non-null     float64
 3   Purchased  20 non-null     str
dtypes: float64(2), str(2)
memory usage: 772.0 bytes

In [14]:
dataset.head()

   Country   Age   Salary Purchased
0    Spain  44.0  72000.0        No
1  Germany  27.0  48000.0       Yes
2    India  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

# **Lets first fix the missing data**

In [15]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan,strategy="mean")
imputer.fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])

print(X)

[['Spain' 44.0 72000.0]
 ['Germany' 27.0 48000.0]
 ['India' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63411.76470588235]
 ['India' 35.0 58000.0]
 ['Spain' 37.1764705882353 52000.0]
 ['Germany' 48.0 79000.0]
 ['India' 50.0 83000.0]
 ['Spain' 37.0 67000.0]
 ['Africa' 29.0 63411.76470588235]
 ['Germany' 33.0 59000.0]
 ['India' 37.1764705882353 49000.0]
 ['Spain' 42.0 71000.0]
 ['Africa' 45.0 76000.0]
 ['Germany' 31.0 55000.0]
 ['India' 28.0 63411.76470588235]
 ['Spain' 37.1764705882353 64000.0]
 ['Africa' 39.0 62000.0]
 ['Germany' 36.0 68000.0]]

# **Lets now OneHotEncode the labels**

In [19]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct=ColumnTransformer(transformers=[("encoder",OneHotEncoder(),[0])],remainder="passthrough")

X=ct.fit_transform(X)

In [20]:
X

array([[0.0, 0.0, 0.0, 1.0, 44.0, 72000.0],
       [0.0, 1.0, 0.0, 0.0, 27.0, 48000.0],
       [0.0, 0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 0.0, 40.0, 63411.76470588235],
       [0.0, 0.0, 1.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 0.0, 1.0, 37.1764705882353, 52000.0],
       [0.0, 1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 0.0, 0.0, 1.0, 37.0, 67000.0],
       [1.0, 0.0, 0.0, 0.0, 29.0, 63411.76470588235],
       [0.0, 1.0, 0.0, 0.0, 33.0, 59000.0],
       [0.0, 0.0, 1.0, 0.0, 37.1764705882353, 49000.0],
       [0.0, 0.0, 0.0, 1.0, 42.0, 71000.0],
       [1.0, 0.0, 0.0, 0.0, 45.0, 76000.0],
       [0.0, 1.0, 0.0, 0.0, 31.0, 55000.0],
       [0.0, 0.0, 1.0, 0.0, 28.0, 63411.76470588235],
       [0.0, 0.0, 0.0, 1.0, 37.1764705882353, 64000.0],
       [1.0, 0.0, 0.0, 0.0, 39.0, 62000.0],
       [0.0, 1.0, 0.0, 0.0, 36.0, 68000.0]], dtype=object)